FROM eclipse-temurin:17-jdk-focal

WORKDIR /app

COPY pom.xml ./
COPY mvnw ./
COPY .mvn .mvn
RUN apt-get update && apt-get install -y maven && rm -rf /var/lib/apt/lists/*

COPY src ./src

EXPOSE 8080

CMD ["./mvnw", "spring-boot:run"]